services:
  - type: web
    name: task-analyzer-backend
    runtime: python
    region: singapore
    plan: free

    buildCommand: |
      pip install --upgrade pip
      pip install whitenoise
      pip install -r requirements.txt
      python backend/manage.py collectstatic --noinput

    startCommand: |
      gunicorn backend.task_analyzer.wsgi:application --bind 0.0.0.0:$PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.10
